[package]
name = "multisig-interact"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@multiversx.com>"]
edition = "2021"
publish = false

[[bin]]
name = "multisig-interact"
path = "src/multisig_interact.rs"

[dependencies]
clap = { version = "4.1.0", features = ["derive", "cargo"] }

[dependencies.multisig]
path = ".."

[dependencies.multiversx-sc-modules]
version = "0.39.5"
path = "../../../../contracts/modules"

[dependencies.multiversx-sc-snippets]
version = "0.39.5"
path = "../../../../framework/snippets"
