name = "adder"

rename_pairs = [
    [
        "blockchain.set_current_dir_from_workspace(\"contracts/examples/adder\");",
        "// blockchain.set_current_dir_from_workspace(\"relative path to your workspace, if applicable\");",
    ],
]
