gateway = 'https://testnet-gateway.multiversx.com'
call_type = "LegacyAsync" # Sync / LegacyAsync / TransferExecute
token_id = "EGLD" # EGLD / esdt_token_id
token_nonce = 0 # is 0 if fungible
amount = '50000000000000000'